# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RO0cVPxkX8cJDUQ0xze6G01u1ouNH-9z
"""

a= [2,4,6,8,10]
for i in a:
  print("the square of", i ,"=", i**2)
  print("the cube of  ", i ,"=", i**3)
  print("*****************************")

